require 'io'
io.stdout:write('testing io_test... ')
require 'tests.io_test'
print 'OK!'

io.stdout:write('testing libc_test... ')
require 'tests.libc_test'
print 'OK!'

io.stdout:write('testing math_test... ')
require 'tests.math_test'
print 'OK!'

io.stdout:write('testing memory_test... ')
require 'tests.memory_test'
print 'OK!'

io.stdout:write('testing allocators_test... ')
require 'tests.allocators_test'
print 'OK!'

io.stdout:write('testing raii_test2... ')
require 'tests.raii_test2'
print 'OK!'

io.stdout:write('testing raii_test... ')
require 'tests.raii_test'
print 'OK!'

io.stdout:write('testing require_test_dep... ')
require 'tests.require_test_dep'
print 'OK!'

io.stdout:write('testing require_test... ')
require 'tests.require_test'
print 'OK!'

io.stdout:write('testing resourcepool_test... ')
require 'tests.resourcepool_test'
print 'OK!'

io.stdout:write('testing sequence_test... ')
require 'tests.sequence_test'
print 'OK!'

io.stdout:write('testing span_test... ')
require 'tests.span_test'
print 'OK!'

io.stdout:write('testing string_test... ')
require 'tests.string_test'
print 'OK!'

io.stdout:write('testing stringbuilder_test... ')
require 'tests.stringbuilder_test'
print 'OK!'

io.stdout:write('testing traits_test... ')
require 'tests.traits_test'
print 'OK!'

io.stdout:write('testing vector_test... ')
require 'tests.vector_test'
print 'OK!'

 -- must be last for now because replace some globals
io.stdout:write('testing basic_test... ')
require 'tests.basic_test'
print 'OK!'

-- must be the last test because it calls os.exit()
io.stdout:write('testing os_test...\n')
require 'tests.os_test'
