require 'allocators.gc'
require 'memory'

local function alloc_test() <noinline>
  for i=1,128 do
    local p = gc_allocator:alloc(1024)
    if i == 1 then
      assert(gc:count() == 1)
    end
    assert(p ~= nilptr)
    p = nilptr
  end
end

local function clear_stack() <noinline>
  local buffer: [1024]byte <volatile>
end

do -- gc
  assert(gc:isrunning())
  gc:stop()
  assert(not gc:isrunning())
  gc:restart()
  assert(gc:isrunning())
  alloc_test()
  clear_stack()
  gc:collect()
  assert(gc:count() == 0)
end

do -- collectgarbage
  assert(collectgarbage("isrunning"))
  collectgarbage("stop")
  assert(not collectgarbage("isrunning"))
  collectgarbage("restart")
  assert(collectgarbage("isrunning"))
  alloc_test()
  clear_stack()
  collectgarbage("collect")
  assert(collectgarbage("count") == 0)
end
