require 'allocators.gc'
require 'memory'

local function alloc_test() <noinline>
  for i=1,128 do
    local p <volatile> = gc_allocator:alloc(1024)
    assert(p ~= nilptr)
    p = nilptr
  end
end

local function clear_stack() <noinline>
  local buffer: [1024]byte <volatile>
end

do -- gc
  assert(gc:isrunning())
  gc:stop()
  assert(not gc:isrunning())
  gc:restart()
  assert(gc:isrunning())
  alloc_test()
  clear_stack()
  gc:collect()
  gc:collect()
  assert(gc:count() < 16)
end

do -- collectgarbage
  assert(collectgarbage("isrunning"))
  collectgarbage("stop")
  assert(not collectgarbage("isrunning"))
  collectgarbage("restart")
  assert(collectgarbage("isrunning"))
  alloc_test()
  clear_stack()
  collectgarbage()
  collectgarbage("collect")
  assert(collectgarbage("count") < 16)
end

local gc_count = 0
do -- finalizers
  local function finalizer_test(count: boolean) <noinline>
    local Foo = @record{count: boolean}

    function Foo:__gc()
      if self.count then
        gc_count = gc_count + 1
      end
    end

    local foo: *Foo = gc_allocator:new(Foo{count=count})
    local foos: span(Foo) = gc_allocator:new(Foo{count=count}, 2)
    foos = (@span(Foo)){}
    foo = nilptr
  end
  finalizer_test(true)
  finalizer_test(false)
  alloc_test()
  clear_stack()
  collectgarbage()
  collectgarbage()
  assert(gc_count == 3)
end
