## strict = true

--## cflags '-fsanitize=address -fsanitize=undefined'

require 'memory'
require 'allocators.generic_allocator'

local allocator = @generic_allocator

-- utilities
local vec2 = @record{x: integer, y: integer}

--------------------------------------------------------------------------------
-- raw pointers

do -- alloc and dealloc
  local p = allocator.alloc(4)
  assert(p)
  allocator.dealloc(p)
  p = nilptr
  allocator.dealloc(p)
end

do -- alloc0
  local p = (@vec2*)(allocator.alloc0(#@vec2))
  assert(p)
  assert(p.x == 0 and p.y == 0)
  allocator.dealloc(p)
end

do -- realloc
  local p = allocator.alloc(1)
  assert(p)
  p = allocator.realloc(p, 4)
  assert(p)
  p = allocator.realloc(p, 1)
  allocator.dealloc(p)
end

do -- realloc0
  local p = (@vec2[0]*)(allocator.alloc0(#@vec2))
  assert(p)
  assert(p[0].x == 0 and p[0].y == 0)
  p[0] = vec2{x=1, y=2}
  p = (@vec2[0]*)(allocator.realloc0(p, 2*#@vec2, #@vec2))
  assert(p)
  assert(p[0].x == 1 and p[0].y == 2)
  assert(p[1].x == 0 and p[1].y == 0)
  p = (@vec2[0]*)(allocator.realloc0(p, #@vec2, #@vec2))
  assert(p)
  assert(p[0].x == 1 and p[0].y == 2)
  p = (@vec2[0]*)(allocator.realloc0(p, #@vec2, 0))
  assert(p)
  assert(p[0].x == 0 and p[0].y == 0)
  allocator.dealloc(p)
end

do -- copy
  local pa = (@vec2*)(allocator.alloc0(#@vec2))
  local pb = (@vec2*)(allocator.alloc0(#@vec2))
  $pa = {x=1,y=2}
  memory.copy(pb, pa, #@vec2)
  assert(pb.x == 1 and pb.y == 2)
  allocator.dealloc(pa)
  allocator.dealloc(pb)
end

do -- move
  local p = (@vec2[0]*)(allocator.alloc0(2*#@vec2))
  local pa, pb = &p[0], &p[1]
  $pa, $pb = {x=1,y=2}, {x=3,y=4}
  memory.move(&((@integer[0]*)(p))[1], p, 3 * #@integer)
  assert(pa.x == 1 and pa.y == 1 and pb.x == 2 and pb.y == 3)
  allocator.dealloc(p)
end

do -- set and zero
  local p = (@vec2*)(allocator.alloc0(#@vec2))
  memory.set(p, 0xff, #@vec2)
  assert(p.x == 0xffffffffffffffff and p.y == 0xffffffffffffffff)
  memory.zero(p, #@vec2)
  assert(p.x == 0 and p.y == 0)
  allocator.dealloc(p)
end

do -- compare
  local pa = (@vec2*)(allocator.alloc0(#@vec2))
  local pb = (@vec2*)(allocator.alloc0(#@vec2))
  assert(memory.compare(pa, pb, #@vec2) == 0)
  pa.x = 1 pb.x = 2
  assert(memory.compare(pa, pb, #@vec2) == -1)
  pa.x = 2 pb.x = 1
  assert(memory.compare(pa, pb, #@vec2) == 1)
  pa.x = 2 pb.x = 2
  assert(memory.compare(pa, pb, #@vec2) == 0)
  allocator.dealloc(pa)
  allocator.dealloc(pb)
end

do -- equals
  local pa = (@vec2*)(allocator.alloc0(#@vec2))
  local pb = (@vec2*)(allocator.alloc0(#@vec2))
  assert(memory.equals(pa, pb, #@vec2))
  pa.x = 1
  assert(not memory.equals(pa, pb, #@vec2))
  allocator.dealloc(pa)
  allocator.dealloc(pb)
end

do -- scan
  local p = (@vec2*)(allocator.alloc0(#@vec2))
  p.x = 1 p.y = 2
  assert(memory.scan(p, 1, #@vec2) == &p.x)
  assert(memory.scan(p, 2, #@vec2) == &p.y)
  assert(memory.scan(p, 3, #@vec2) == nilptr)
  allocator.dealloc(p)
end

do -- contains
  local p = (@vec2*)(allocator.alloc0(#@vec2))
  p.x = 1 p.y = 2
  assert(memory.contains(p, 0, #@vec2))
  assert(memory.contains(p, 1, #@vec2))
  assert(memory.contains(p, 2, #@vec2))
  assert(not memory.contains(p, 3, #@vec2))
  allocator.dealloc(p)
end

--------------------------------------------------------------------------------
-- span

do -- spanalloc and spandealloc
  local p = allocator.spanalloc(@vec2, 2)
  assert(p.data ~= nilptr and p.size == 2)
  allocator.spandealloc(p)
  p = (@span(vec2)){}
  assert(p.data == nilptr and p.size == 0)
  allocator.spandealloc(p)
  p = allocator.spanalloc(@vec2, 0)
  assert(p.data == nilptr and p.size == 0)
end

do -- spanalloc0
  local p = allocator.spanalloc0(@vec2, 2)
  assert(p.data ~= nilptr and p.size == 2)
  assert(p[0].x == 0 and p[0].y == 0)
  assert(p[1].x == 0 and p[1].y == 0)
  allocator.spandealloc(p)
  p = allocator.spanalloc0(@vec2, 0)
  assert(p.data == nilptr and p.size == 0)
end

do -- spanrealloc
  local p = allocator.spanalloc(@vec2, 1)
  assert(p.data ~= nilptr and p.size == 1)
  p = allocator.spanrealloc(p, 4)
  assert(p.data ~= nilptr and p.size == 4)
  p = allocator.spanrealloc(p, 1)
  assert(p.data ~= nilptr and p.size == 1)
  p = allocator.spanrealloc(p, 0)
  assert(p.data == nilptr and p.size == 0)
  allocator.spandealloc(p)
  assert(p.data == nilptr and p.size == 0)
end

do -- spanrealloc0
  local p = allocator.spanalloc0(@vec2, 1)
  assert(p.data ~= nilptr and p.size == 1)
  assert(p[0].x == 0 and p[0].y == 0)
  p[0] = vec2{x=1, y=2}
  p = allocator.spanrealloc0(p, 2)
  assert(p.data ~= nilptr and p.size == 2)
  assert(p[0].x == 1 and p[0].y == 2)
  assert(p[1].x == 0 and p[1].y == 0)
  p = allocator.spanrealloc0(p, 1)
  assert(p.data ~= nilptr and p.size == 1)
  assert(p[0].x == 1 and p[0].y == 2)
  p = allocator.spanrealloc0(p, 0)
  assert(p.data == nilptr and p.size == 0)
  allocator.spandealloc(p)
end

do -- spancopy
  local pa = allocator.spanalloc0(@vec2, 1)
  local pb = allocator.spanalloc0(@vec2, 1)
  pa[0] = {x=1,y=2}
  memory.spancopy(pb, pa)
  assert(pb[0].x == 1 and pb[0].y == 2)
  allocator.spandealloc(pa)
  allocator.spandealloc(pb)
end

do -- spanmove
  local p = allocator.spanalloc0(@vec2, 2)
  local pa, pb = &p[0], &p[1]
  $pa, $pb = {x=1,y=2}, {x=3,y=4}
  local sb = (@span(integer))({ data=&(((@integer[0]*)(p.data))[0]), size=3 })
  local db = (@span(integer))({ data=&(((@integer[0]*)(p.data))[1]), size=3 })
  memory.spanmove(db, sb)
  --assert(pa.x == 1 and pa.y == 1 and pb.x == 2 and pb.y == 3)
  allocator.spandealloc(p)
end

do -- spanset and spanzero
  local p = allocator.spanalloc0(@vec2, 2)
  memory.spanset(p, (@vec2){x=1,y=2})
  assert(p[0].x == 1 and p[0].y == 2)
  assert(p[1].x == 1 and p[1].y == 2)
  memory.spanzero(p)
  assert(p[0].x == 0 and p[0].y == 0)
  assert(p[1].x == 0 and p[1].y == 0)
  allocator.spandealloc(p)
end

do -- spancompare
  local pa = allocator.spanalloc0(@vec2, 1)
  local pb = allocator.spanalloc0(@vec2, 1)
  local pc = allocator.spanalloc0(@vec2, 0)
  assert(memory.spancompare(pa, pb) == 0)
  pa[0].x = 1 pb[0].x = 2
  assert(memory.spancompare(pa, pb) == -1)
  assert(memory.spancompare(pb, pa) == 1)
  pa[0].x = 2 pb[0].x = 1
  assert(memory.spancompare(pa, pb) == 1)
  assert(memory.spancompare(pb, pa) == -1)
  pa[0].x = 2 pb[0].x = 2
  assert(memory.spancompare(pa, pb) == 0)
  assert(memory.spancompare(pa, pc) == 1)
  assert(memory.spancompare(pc, pa) == -1)
  allocator.spandealloc(pa)
  allocator.spandealloc(pb)
  allocator.spandealloc(pc)
end

do -- spanequals
  local pa = allocator.spanalloc0(@vec2, 1)
  local pb = allocator.spanalloc0(@vec2, 1)
  assert(memory.spanequals(pa, pb))
  pa[0].x = 1
  assert(not memory.spanequals(pa, pb))
  allocator.spandealloc(pa)
  allocator.spandealloc(pb)
end

do -- spanscan
  local p = allocator.spanalloc0(@vec2, 2)
  p[0].x = 1 p[0].y = 2
  p[1].x = 3 p[1].y = 4
  assert(memory.spanscan(p, (@vec2){1,2}) == 0)
  assert(memory.spanscan(p, (@vec2){3,4}) == 1)
  assert(memory.spanscan(p, (@vec2){5,6}) == -1)
  allocator.spandealloc(p)
end

do -- spancontains
  local p = allocator.spanalloc0(@vec2, 2)
  p[0].x = 1 p[0].y = 2
  p[1].x = 3 p[1].y = 4
  assert(memory.spancontains(p, (@vec2){1,2}))
  assert(memory.spancontains(p, (@vec2){3,4}))
  assert(not memory.spancontains(p, (@vec2){5,6}))
  allocator.spandealloc(p)
end

--------------------------------------------------------------------------------
-- new and delete

do -- new for pointers
  local v = allocator.new(@vec2)
  assert(v.x == 0 and v.y == 0)
  v.x = 1 v.y = 2
  assert(v.x == 1 and v.y == 2)
  allocator.delete(v)
end

do -- new for spans
  local v = allocator.new(@vec2, 2)
  assert(v[0].x == 0 and v[0].y == 0)
  assert(v[1].x == 0 and v[1].y == 0)
  v[0].x = 1 v[0].y = 2
  v[1].x = 3 v[1].y = 4
  assert(v[0].x == 1 and v[0].y == 2)
  assert(v[1].x == 3 and v[1].y == 4)
  allocator.delete(v)
end
