## context.pragmas.unitname = ''

local Obj  = @record{
  id: integer
}

local dcount: integer = 0
function Obj:__destroy()
  --print('destroy', self.id)
  assert(self.id ~= 0)
  dcount = dcount + self.id
end

local ccount: integer = 0
function Obj:__copy(): Obj
  --print('copy', self.id)
  assert(self.id ~= 0)
  ccount = ccount + self.id
  return $self
end

local function reset()
  dcount = 0
  ccount = 0
end

------------------------------------------------------------------------
-- test destroy on scope termination

do reset()
  local a: Obj = {1}
end
assert(dcount == 1)

do reset()
  local a: Obj
  a.id = 1
end
assert(dcount == 1)

do
  local function f()
    local o: Obj = {1}
  end

  do reset()
    f()
    assert(dcount == 1)
  end
end

do
  local function f(o: Obj)
  end

  do reset()
    f({1})
    assert(dcount == 1)
  end
end

------------------------------------------------------------------------
-- test destroy bypass on function returns

do
  local function f(o: Obj): Obj
    return o
  end

  do reset()
    f({1})
    assert(dcount == 1)
  end

  do reset()
    local o: Obj = f({1})
    assert(dcount == 0)
  end
  assert(dcount == 1)
end
do
  local function f(): (Obj, Obj)
    local a: Obj, b: Obj = {1}, {2}
    return a, b
  end
  local function ff(): (Obj, Obj)
    return f(), Obj{4}
  end
  local function fff(): (Obj, Obj)
    return Obj{4}, f()
  end
  local function ffff(): (Obj, Obj)
    return f()
  end
  local function fffff(): Obj
    return f()
  end

  do reset()
    f()
    assert(dcount == 3)
  end

  do reset()
    local a, b = f()
    assert(dcount == 0)
  end
  assert(dcount == 3)

  do reset()
    local a = f()
    assert(dcount == 2)
  end
  assert(dcount == 3)

  do reset()
    f()
    assert(dcount == 3)
  end

  do reset()
    ff()
    assert(dcount == 7)
  end
  assert(dcount == 7)

  do reset()
    fff()
    assert(dcount == 7)
  end

  do reset()
    ffff()
    assert(dcount == 3)
  end

  do reset()
    fffff()
    assert(dcount == 3)
  end
end

do
  local function f(): (Obj, Obj, Obj)
    local a: Obj, b: Obj, c: Obj = {1}, {2}, {4}
    return a, b, c
  end
  local function ff(): (Obj, Obj)
    return f()
  end
  local function fff(): (Obj)
    return f()
  end

  do reset()
    f()
    assert(dcount == 7)
  end

  do reset()
    ff()
    assert(dcount == 7)
  end

  do reset()
    fff()
    assert(dcount == 7)
  end

  do reset()
    local a = f()
    assert(dcount == 6)
  end
end

------------------------------------------------------------------------
-- test destroy on early returns

do
  local function f()
    local a: Obj = {1}
    if true then
      return
    end
  end

  do reset()
    f()
    assert(dcount == 1)
  end
end

do
  local function f(o0: Obj, b: boolean)
    local o1: Obj = {2}
    do
      local o2: Obj = {4}
      if b then
        local o3: Obj = {8}
        return
      end
      local o4: Obj = {16}
    end
    local o5: Obj = {32}
  end

  do reset()
    f({1}, true)
    assert(dcount == 1+2+4+8)
    reset()
    f({1}, false)
    assert(dcount == 1+2+4+16+32)
  end
end

------------------------------------------------------------------------
-- test destroy on break and continue

do reset()
  for i=1,10 do
    local o1: Obj = {1}
    if i == 2 then
      local o2: Obj = {2}
      break
    end
    local o3: Obj = {4}
  end
  assert(dcount == 1+4+1+2)
end

------------------------------------------------------------------------
-- test nested destroy

do
  local ParentObj = @record {
    o: Obj
  }
  do reset()
    local a: ParentObj = {{1}}
  end
  assert(dcount == 1)
end
