require 'stringbuilder'
require 'allocators.arena'

do
  local sb: stringbuilder
  sb:write('hello world')
  sb:writebyte('\n'_byte)
  sb:writef('%d\n', 10)
  sb:writef('%.2f\n', 3.14)
  sb:writef('%s %d', 'hi', 1)
  local s = sb:prepare(1)
  s[0] = '\n'_byte
  sb:commit(1)
  local s: string = tostring(sb)
  assert(s == "hello world\n10\n3.14\nhi 1\n")
  assert(sb:view() == s)
  s:destroy()
  sb:destroy()
end

do -- write
  local sb: stringbuilder
  sb:write('a', 'b', 2, true)
  assert(sb:view() == 'ab2true')
  sb:destroy()
end

do -- using a custom allocator
  local allocator: ArenaAllocator(256, 1)
  local sb = (@stringbuilder(*ArenaAllocator(256, 1))).make(&allocator)
  sb:write('hello')
  local s: string = tostring(sb)
  assert(s == "hello")
  s:destroy()
  -- sb does not need to be destroyed because we are using an arena allocator
end
