require 'stringbuilder'
require 'allocators.arena'

do
  local sb: stringbuilder
  sb:write_string('hello world')
  sb:write_byte('\n'_byte)
  sb:write_format('%d\n', 10)
  sb:write_format('%.2f\n', 3.14)
  sb:write_format('%s %d', 'hi', 1)
  sb:prepare(1)[0] = '\n'_byte
  sb:commit(1)
  local s: string = tostring(sb)
  assert(s == "hello world\n10\n3.14\nhi 1\n")
  assert(sb:view() == s)
  s:destroy()
  sb:destroy()
end

do -- using a custom allocator
  local allocator: ArenaAllocator(256, 1)
  local sb = stringbuilder.make(&allocator)
  sb:write_string('hello')
  local s: string = tostring(sb)
  assert(s == "hello")
  s:destroy()
  sb:destroy()
end
