require 'busted.runner'()

local assert = require 'spec.tools.assert'

describe("Nelua stdlib", function()

it("core", function()
  assert.run_c_from_file('tests/core_test.nelua')
end)
it("traits", function()
  assert.run_c_from_file('tests/traits_test.nelua')
end)
it("libc", function()
  assert.run_c_from_file('tests/libc_test.nelua')
end)
it("math", function()
  assert.run_c_from_file('tests/math_test.nelua')
end)
it("memory", function()
  assert.run_c_from_file('tests/memory_test.nelua')
end)
it("sequence", function()
  assert.run_c_from_file('tests/sequence_test.nelua')
end)
it("vector", function()
  assert.run_c_from_file('tests/vector_test.nelua')
end)
it("span", function()
  assert.run_c_from_file('tests/span_test.nelua')
end)
it("resourcepool", function()
  assert.run_c_from_file('tests/resourcepool_test.nelua')
end)
it("io", function()
  assert.run_c_from_file('tests/io_test.nelua')
end)
it("os", function()
  assert.run_c_from_file('tests/os_test.nelua')
end)
it("string", function()
  assert.run_c_from_file('tests/string_test.nelua')
end)
it("copy/destroy", function()
  assert.run_c_from_file('tests/raii_test.nelua')
  assert.run_c_from_file('tests/raii_test2.nelua')
end)

end)
