local pldir = require 'pl.dir'
local plfile = require 'pl.file'
local plpath = require 'pl.path'
local plutil = require 'pl.utils'
local pltemplate = require 'pl.template'
local config = require 'euluna.configer'.get()
local sha1 = require 'sha1'.sha1
local assertf = require 'euluna.utils'.assertf
local c_compiler = {}

local function get_compile_command(infile, outfile)
  local env = {infile = infile, outfile = outfile}
  env.cc = os.getenv('CC')
  env.cflags = os.getenv('CFLAGS')
  env.ldflags = os.getenv('LDFLAGS')
  setmetatable(env, {__index = config})
  return pltemplate.substitute("$(cc) $(cflags) -o $(outfile) $(ldflags) $(infile)", env)
end

local last_ccinfo
local function get_cc_info()
  if last_ccinfo then return last_ccinfo end
  local ccinfocmd = string.format("%s -v -x c -E /dev/null", config.cc)
  local ok, ret, stdout, ccinfo = plutil.executeex(ccinfocmd)
  assertf(ok and ret == 0, "failed to retrive compiler information:\n%s", ccinfo)
  last_ccinfo = ccinfo
  return ccinfo
end

local function hash_compilation(ccode)
  local dummycmd = get_compile_command('dummy.c', 'dummy')
  local ccinfo = get_cc_info()
  return sha1(string.format("%s%s%s", ccode, ccinfo, dummycmd))
end

function c_compiler.compile_code(ccode, outfile)
  local cfile = outfile .. '.c'

  -- create output directory if needed
  local outdir = plpath.dirname(cfile)
  pldir.makepath(outdir)

  -- file heading
  local hash = hash_compilation(ccode)
  local heading = string.format(
[[/* This file was auto generated by Euluna. */
/* Compile Hash: %s */

]], hash)
  local sourcecode = heading .. ccode

  -- check if write is actually needed
  local current_sourcecode = plfile.read(cfile)
  if not config.no_cache and current_sourcecode and current_sourcecode == sourcecode then
    if not config.quiet then print("using cached generated " .. cfile) end
    return cfile
  end

  -- save sources to a file
  assert(plfile.write(cfile, sourcecode))
  if not config.quiet then print("generated " .. cfile) end

  return cfile
end

function c_compiler.compile_binary(cfile, outfile)
  -- if the file with that hash already exists skip recompiling it
  if not config.no_cache then
    local cfile_mtime = plfile.modified_time(cfile)
    local outfile_mtime = plfile.modified_time(outfile)
    if cfile_mtime and outfile_mtime and cfile_mtime <= outfile_mtime then
      if not config.quiet then
        print("using cached binary " .. outfile)
      end
      return outfile
    end
  end

  -- create output directory if needed
  local outdir = plpath.dirname(outfile)
  pldir.makepath(outdir)

  -- generate compile command
  local cmd = get_compile_command(cfile, outfile)
  if not config.quiet then print(cmd) end

  -- compile the file
  local ok, ret, stdout, stderr = plutil.executeex(cmd)
  if stdout and not config.quiet and #stdout > 0 then io.stdout:write(stdout) end
  assertf(ok and ret == 0, "compilation failed:\n%s", stderr)

  return outfile
end

function c_compiler.get_run_command(binaryfile)
  return './' .. binaryfile
end

return c_compiler
