local pegger = require 'euluna.utils.pegger'
local stringer = require 'euluna.utils.stringer'
local fs = require 'euluna.utils.fs'
local metamagic = require 'euluna.utils.metamagic'
local except = require 'euluna.utils.except'
local executor = require 'euluna.utils.executor'
local config = require 'euluna.configer'.get()

local compiler = {}

local function get_runtime_cfile()
  return fs.join(config.runtime_path, 'c', 'euluna_core.c')
end
local function get_runtime_hfile()
  return fs.join(config.runtime_path, 'c', 'euluna_core.h')
end
local function get_runtime_include_path()
  return fs.join(config.runtime_path, 'c')
end

local function get_compile_command(infile, outfile)
  local env = { infile = infile, outfile = outfile }
  env.cc = os.getenv('CC')
  env.cflags = os.getenv('CFLAGS')
  env.ldflags = os.getenv('LDFLAGS')
  metamagic.setmetaindex(env, config)
  env.runtime_cflags = string.format('-I "%s"', get_runtime_include_path())
  env.runtime_file = get_runtime_cfile()
  return pegger.substitute(
    '$(cc) $(runtime_cflags) $(cflags) $(ldflags) -o "$(outfile)" "$(infile)" "$(runtime_file)"',
    env)
end

local last_ccinfos = {}
local function get_cc_info()
  local ccinfocmd = string.format("%s -v -x c -E /dev/null", config.cc)
  local last_ccinfo = last_ccinfos[ccinfocmd]
  if last_ccinfo then return last_ccinfo end
  local ok, ret, stdout, ccinfo = executor.execex(ccinfocmd)
  except.assertraisef(ok and ret == 0, "failed to retrive compiler information: %s", ccinfo or '')
  last_ccinfos[ccinfocmd] = ccinfo
  return ccinfo
end

local function hash_compilation(ccode)
  local dummycmd = get_compile_command('dummy.c', 'dummy')
  local ccinfo = get_cc_info()
  local runtime_hcode = fs.readfile(get_runtime_hfile())
  local runtime_ccode = fs.readfile(get_runtime_cfile())
  return stringer.sha1(string.format("%s%s%s%s%s", runtime_hcode, runtime_ccode, ccode, ccinfo, dummycmd))
end

function compiler.compile_code(ccode, outfile)
  local cfile = outfile .. '.c'

  -- file heading
  local hash = hash_compilation(ccode)
  local heading = string.format(
[[/* This file was auto generated by Euluna. */
/* Compile Hash: %s */

]], hash)
  local sourcecode = heading .. ccode

  -- check if write is actually needed
  local current_sourcecode = fs.tryreadfile(cfile)
  if not config.no_cache and current_sourcecode and current_sourcecode == sourcecode then
    if not config.quiet then print("using cached generated " .. cfile) end
    return cfile
  end

  fs.ensurefilepath(cfile)
  fs.writefile(cfile, sourcecode)
  if not config.quiet then print("generated " .. cfile) end

  return cfile
end

function compiler.compile_binary(cfile, outfile)
  -- if the file with that hash already exists skip recompiling it
  if not config.no_cache then
    local cfile_mtime = fs.getfiletime(cfile)
    local outfile_mtime = fs.getfiletime(outfile)
    if cfile_mtime and outfile_mtime and cfile_mtime <= outfile_mtime then
      if not config.quiet then
        print("using cached binary " .. outfile)
      end
      return outfile
    end
  end

  fs.ensurefilepath(outfile)

  -- generate compile command
  local cmd = get_compile_command(cfile, outfile)
  if not config.quiet then print(cmd) end

  -- compile the file
  local success, status, stdout, stderr = executor.execex(cmd)
  except.assertraisef(success and status == 0,
    "C compilation for '%s' failed:\n%s", outfile, stderr or '')

  if stderr then
    io.stderr:write(stderr)
  end

  return outfile
end

function compiler.get_run_command(binaryfile)
  return './' .. binaryfile
end

return compiler
