local pegger = require 'euluna.utils.pegger'
local stringer = require 'euluna.utils.stringer'
local fs = require 'euluna.utils.fs'
local metamagic = require 'euluna.utils.metamagic'
local except = require 'euluna.utils.except'
local executor = require 'euluna.utils.executor'
local tabler = require 'euluna.utils.tabler'
local config = require 'euluna.configer'.get()
local cdefs = require 'euluna.cdefs'

local compiler = {}

local function get_compile_args(infile, outfile)
  local env = { infile = infile, outfile = outfile }
  local compiler_flags = cdefs.compilers_flags[config.cc] or cdefs.compiler_base_flags
  metamagic.setmetaindex(env, config)
  env.cflags_base = compiler_flags.cflags_base
  env.cflags_build = (config.release and compiler_flags.cflags_release or compiler_flags.cflags_debug)
  return pegger.substitute(
    '$(cc) $(cflags_base) $(cflags_build) $(cflags) -o "$(outfile)" "$(infile)"',
    env)
end

local last_ccinfos = {}
local function get_cc_info()
  local cccmd = string.format('%s -v -x c -E /dev/null', config.cc)
  local last_ccinfo = last_ccinfos[config.cc]
  if last_ccinfo then return last_ccinfo end
  local ok, ret, stdout, ccinfo = executor.execex(cccmd)
  except.assertraisef(ok and ret == 0, "failed to retrive compiler information: %s", ccinfo or '')
  last_ccinfos[config.cc] = ccinfo
  return ccinfo
end

local function hash_compilation(ccode)
  local cccmd = get_compile_args('dummy.c', 'dummy')
  local ccinfo = get_cc_info()
  return stringer.hash(string.format("%s%s%s", ccode, ccinfo, cccmd))
end

function compiler.compile_code(ccode, outfile)
  local cfile = outfile .. '.c'

  -- file heading
  local hash = hash_compilation(ccode)
  local heading = string.format(
[[/* This file was auto generated by Euluna. */
/* Compile Hash: %s */

]], hash)
  local sourcecode = heading .. ccode

  -- check if write is actually needed
  local current_sourcecode = fs.tryreadfile(cfile)
  if not config.no_cache and current_sourcecode and current_sourcecode == sourcecode then
    if not config.quiet then print("using cached generated " .. cfile) end
    return cfile
  end

  fs.ensurefilepath(cfile)
  fs.writefile(cfile, sourcecode)
  if not config.quiet then print("generated " .. cfile) end

  return cfile
end

function compiler.compile_binary(cfile, outfile)
  -- if the file with that hash already exists skip recompiling it
  if not config.no_cache then
    local cfile_mtime = fs.getfiletime(cfile)
    local outfile_mtime = fs.getfiletime(outfile)
    if cfile_mtime and outfile_mtime and cfile_mtime <= outfile_mtime then
      if not config.quiet then
        print("using cached binary " .. outfile)
      end
      return outfile
    end
  end

  fs.ensurefilepath(outfile)

  -- generate compile command
  local cccmd = get_compile_args(cfile, outfile)
  if not config.quiet then print(cccmd) end

  -- compile the file
  local success, status, stdout, stderr = executor.execex(cccmd)
  except.assertraisef(success and status == 0,
    "C compilation for '%s' failed:\n%s", outfile, stderr or '')

  if stderr then
    io.stderr:write(stderr)
  end

  return outfile
end

function compiler.get_run_command(binaryfile, runargs)
  return fs.abspath(binaryfile), tabler.copy(runargs)
end

return compiler
